// app_react/src/Components/Salas/salaLayout.js
import React, { useEffect, useState } from "react";
import Navbar from "../../Layouts/NavBar";
import { Link } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { setSala, setDisable, reset } from "../../redux/salaSlice";
import Box from "./box";
import axiosCliente from "../../Config/axiosCliente";
import Swal from "sweetalert2";


const SalaLayout = (props) => {

    const { id, row, column, disable } = useSelector(state => state.salaLayout) || props  
    const fila = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    var stantx = [];
    var stanty = [];
    const [sillas, setSillas] = useState([])
    useEffect(() => {
        buildGrid()
    }, [])
    const GuardarSillas=async()=>{ 
        const ob={
            disable:disable
        }
        await axiosCliente.put(`/update-sillas/${id}`,ob).then(res=>{
            if(res.status===200){
                Swal.fire(
                    'Modificar sala',
                    res.data.message,
                    'success'
                )
                props.history.push('/listaSalas') 
            }else{
                Swal.fire(
                    'Modificar sala',
                    res.data.message,
                    'error'
                )
                props.history.push('/listaSalas') 
            }
        })
    }
    const buildGrid = async () => {
        for (let i = 0; i < row; i++) {
            for (let j = 0; j < column; j++) {
                stantx.push(
                    <Box disable={false} f={fila[i]} c={j} key={fila[i] + j} type=''>   </Box>
                );
            }
            stanty.push(stantx);
            stantx = [];

        }
        if(disable){
            disable.split(',').map(item => { 
                if(item.length===3){
                    stanty[fila.indexOf(item[0])][item[1]+item[2]] = <Box disable={true} f={fila[fila.indexOf(item[0])]} c={item[1]+item[2]} key={item} type=''>   </Box>
                }else{
                    stanty[fila.indexOf(item[0])][item[1]] = <Box disable={true} f={fila[fila.indexOf(item[0])]} c={item[1]} key={item} type=''>   </Box>
                }  
            })
        }
        setSillas(stanty)

    }

    return (
        <>
            <div className=" min-h-screen bg-gray-900">
                <Navbar className=" h-full" type={"sala"} />
                <section className=" h-full">
                    <div className="flex justify-center items-center my-4">
                        <h1 className="  text-white text-xl   text-center">Sala layout</h1>
                        <button 
                        onClick={GuardarSillas}
                        type="button"
                        to="/agregarSala"
                        className=" border border-blue-500 bg-blue-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-blue-600 focus:outline-none focus:shadow-outline"
                    >
                        Guardar
                    </button>
                    </div>
                    <div className="flex justify-center items-center">
                        <div className=" ">
                            {

                                sillas.map((silla, index) => {
                                    return (
                                        <div key={index} className="flex">
                                            <div className="flex flex-row w  w-full  pb-2">
                                                {
                                                    silla.map((item, index) => { return ([item]) })
                                                }
                                            </div>

                                        </div>

                                    );
                                })
                            }
                        </div>
                    </div>
                </section>
            </div>
        </>
    );
}
export default SalaLayout;

// app-angular/src/app/components/pages/sala-layout/sala-layout.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { BoxModule } from '@app/components/others/box/box.module';
import { ServiceFuncionesService } from '@app/shared/services/service-funciones.service';
import { HttpClient } from '@angular/common/http';
import { take, tap } from 'rxjs/operators';
import { ToastrService } from 'ngx-toastr';
@Component({
  selector: 'app-sala-layout',
  templateUrl: './sala-layout.component.html',
  styleUrls: ['./sala-layout.component.css'],
})
export class SalaLayoutComponent implements OnInit {
  data!: any;
  boxlist$ = this.service.listaBox$;

  constructor(
    private router: Router,
    private toastr:ToastrService,
    private service: ServiceFuncionesService,
    private http: HttpClient
  ) {
    const navigation = this.router.getCurrentNavigation();
    this.data = navigation?.extras?.state;
    this.service.buildGrid(this.data.row, this.data.column, this.data.disable,'');
  }

  ngOnInit(): void {}
  onSave(): void { 
    try {
      this.http
        .put<any>('http://localhost:9090/update-sillas/'+this.data.id, {
          disable: this.service.getDisableBox(),
        })
        .pipe(
          take(1),
          tap(
            (data) => { 
              this.toastr.success('Alerta', 'Se modifico', {
                closeButton: true,
                progressBar: true,
                timeOut: 1500,
              });
              this.router.navigate(['/listasalas']);
            },
            (error) => {
              console.log(error);
            }
          )
        )
        .subscribe();
    } catch (error) {
      console.log(error);
    }
    console.log(this.service.getDisableBox());
  }
}

<div class=" min-h-screen bg-gray-900">
    <app-nav-bar class=" h-full" type="sala" ></app-nav-bar>
    <section class=" h-full">
      <div class="flex justify-center items-center my-4">
        <h1 class="  text-white text-xl   text-center"></h1>
        <button
          type="button"
          (click)='onSave()'
          class=" border border-blue-500 bg-blue-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-blue-600 focus:outline-none focus:shadow-outline"
        >
          Guardar
        </button>
      </div>
      <div class="flex justify-center items-center">

        <div class="">
            <div *ngFor="let items of boxlist$ | async as list" class="flex">
                <div  class="flex">
                  <div  class="flex flex-row w  w-full  pb-2">
                      <app-box *ngFor="let item of items " id={{item.id}} enable={{item.enable}} isReserved={{item.isReserved}}></app-box>
                  </div>
                </div>
        </div>
        
       
        </div>
<!--         <div class=" ">
          {sillas.map((silla, index) => {
            return (
              <div key={index} class="flex">
                <div class="flex flex-row w  w-full  pb-2">
                  {silla.map((item, index) => {
                    return [item];
                  })}
                </div>
              </div>
            );
          })}
        </div> -->
      </div>
    </section>
  </div>
