// app_react/src/Components/Funciones/cardSala.js
import React from "react";

const CardSala = (props) => {
  return (
    <>
      <div className="">
        <div className="bg-white  shadow-lg  border-b-4 border-indigo-500 rounded-2xl overflow-hidden">
          <div className="bg-indigo-500  flex h-16 justify-center  items-center"> 
            <p className="text-white flex">{props.name}</p>
          </div>
          <p className="py-6 px-6 text-lg tracking-wide text-center">
            Capacidad : {props.capacity}
          </p>
          <div className="flex justify-center px-5 mb-2 text-sm ">
            <button
              type="button"
              onClick={()=>props.onSelectSala(props.name,props.id)}
              className="border border-indigo-500 text-indigo-500 rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:text-white hover:bg-indigo-600 focus:outline-none focus:shadow-outline"
            >
             Seleccionar
            </button>
          </div>
        </div>
      </div>
    </>
  );
};
export default CardSala;

// app-angular/src/app/components/others/card-sala/card-sala.component.ts
import { Component, OnInit,Input } from '@angular/core';
import { ServiceFuncionesService } from '@app/shared/services/service-funciones.service';
@Component({
  selector: 'app-card-sala',
  templateUrl: './card-sala.component.html',
  styleUrls: ['./card-sala.component.css']
})
export class CardSalaComponent implements OnInit {
  @Input() id!:string;
  @Input() name!:string;
  @Input() capacidad!:string;
  constructor(
    private service:ServiceFuncionesService
  ) { }

  ngOnInit(): void {
  }
  onSelectSala():void{
    this.service.setSala({'id':this.id,'name':this.name});
  }

}

<div>
  <div class="">
    <div
      class="bg-white shadow-lg border-b-4 border-indigo-500 rounded-2xl overflow-hidden"
    >
      <div class="bg-indigo-500 flex h-16 justify-center items-center">
        <p class="text-white flex">{{ name }}</p>
      </div>
      <p class="py-6 px-6 text-lg tracking-wide text-center">
        Capacidad : {{ capacidad }}
      </p>
      <div class="flex justify-center px-5 mb-2 text-sm">
        <button
          type="button"
          (click)="onSelectSala()"
          class="border border-indigo-500 text-indigo-500 rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:text-white hover:bg-indigo-600 focus:outline-none focus:shadow-outline"
        >
          Seleccionar
        </button>
      </div>
    </div>
  </div>
</div>
