// app_react/src/Components/Peliculas/agregarPelicula.js
import React, { Fragment } from "react";
import NavBar from "../../Layouts/NavBar";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
const AgregarPelicula = () => {
    const { register, errors, handleSubmit } = useForm();
    return (
        <div className=" min-h-screen bg-gray-900">
            <NavBar type={"pelicula"} />
            <section className="max-w-4xl p-6 mx-auto bg-gray-700 rounded-md shadow-md dark:bg-gray-800 mt-20">
                <h1 className="text-xl font-bold text-white capitalize dark:text-white">Nueva pelicula</h1>
                <form>
                    <div className="grid grid-cols-1 gap-6 mt-4 sm:grid-cols-2">
                        <div>
                            <label className="text-white dark:text-gray-200" htmlFor="name">Nombre</label>
                            <input
                                id="name"
                                type="text"
                                className="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                                ref={register({
                                    required: { value: true, message: 'campo requerido' }
                                })} />
                        </div>

                        <div>
                            <label className="text-white dark:text-gray-200" htmlFor="clasificacion">Clasificacion</label>
                            <input id="clasificacion"
                                type="text"
                                className="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                                ref={register({
                                    required: { value: true, message: 'campo requerido' }
                                })} />
                        </div>

                        <div>
                            <label className="text-white dark:text-gray-200" htmlFor="director">Director</label>
                            <input id="director"
                                type="text"
                                className="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                                ref={register({
                                    required: { value: true, message: 'requerido' }
                                })} />
                        </div>

                        <div>
                            <label className="text-white dark:text-gray-200" htmlFor="duracion">Duracion</label>
                            <input
                                id="duracion"
                                type="password"
                                className="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                                ref={register({
                                    required: { value: true, message: 'requerido' }
                                })} />
                        </div>

                    </div>
                    <div className=" w-full">
                        <label className="block text-sm font-medium text-white">
                            Image
                        </label>
                        <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                            <div className="space-y-1 text-center">
                                <svg className="mx-auto h-12 w-12 text-white" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                    <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                                <div className="flex text-sm text-gray-600">
                                    <label htmlFor="file-upload" className="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                                        <span className="">Upload a file</span>
                                        <input id="file-upload" name="file-upload" type="file" className="sr-only" />
                                    </label>
                                    <p className="pl-1 text-white">or drag and drop</p>
                                </div>
                                <p className="text-xs text-white">
                                    PNG, JPG, GIF up to 10MB
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="flex justify-end mt-6">
                        <button
                            type="button"
                            className="border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-red-600 focus:outline-none focus:shadow-outline"
                        >
                            Agregar
                        </button>
                    </div>
                </form>
            </section>

        </div>
    );
}
export default AgregarPelicula;

// app-angular/src/app/components/pages/agregar-pelicula/agregar-pelicula.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,FormControl,Validators } from '@angular/forms';
import { ServiceFuncionesService } from '@app/shared/services/service-funciones.service';

@Component({
  selector: 'app-agregar-pelicula',
  templateUrl: './agregar-pelicula.component.html',
  styleUrls: ['./agregar-pelicula.component.css']
})
export class AgregarPeliculaComponent implements OnInit {

  agregarPeliculaFM = new FormGroup({
    'file':new FormControl(),
    'nombre':new FormControl('',[
      Validators.required,
      Validators.minLength(5)
    ]),
    'clasificacion':new FormControl('',[
      Validators.required,
      Validators.minLength(5)
    ]),
    'director':new FormControl('',[
      Validators.required,
      Validators.minLength(5)
    ]),
    'duracion':new FormControl('',[
      Validators.required,
      Validators.minLength(5)
    ])
  })

  constructor(
    private serviceFunciones:ServiceFuncionesService,
  ) { }

  ngOnInit(): void {
  }

  onSendForm():void{
    try {
      console.log(this.agregarPeliculaFM)
      if(this.agregarPeliculaFM.valid){
        const formData=new FormData()
        formData.append('name',this.agregarPeliculaFM.value.nombre)
        formData.append('image',this.agregarPeliculaFM.value.file[0])
        formData.append('duration',this.agregarPeliculaFM.value.duracion)
        formData.append('classification',this.agregarPeliculaFM.value.clasificacion)
        formData.append('director',this.agregarPeliculaFM.value.director)
        console.log('formData',formData);
      }

    } catch (error) {
      console.log(error);
    }
   
  }
}

<div class=" min-h-screen bg-gray-900">
    <app-nav-bar route='peliculas'> </app-nav-bar> 
    <section class="max-w-4xl p-6 mx-auto bg-gray-700 rounded-md shadow-md dark:bg-gray-800 mt-20">
        <h1 class="text-xl font-bold text-white capitalize dark:text-white">Nueva pelicula</h1>
        <form [formGroup]="agregarPeliculaFM" (ngSubmit)="onSendForm()" >
            <div class="grid grid-cols-1 gap-6 mt-4 sm:grid-cols-2">
                <div>
                    <label class="text-white dark:text-gray-200" htmlFor="name">Nombre</label>
                    <input
                        formControlName="nombre" 
                        id="name"
                        type="text"
                        class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"/>
                </div>

                <div>
                    <label class="text-white dark:text-gray-200" htmlFor="clasificacion">Clasificacion</label>
                    <input id="clasificacion"
                        formControlName="clasificacion" 
                        type="text"
                        class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring" />
                </div>

                <div>
                    <label class="text-white dark:text-gray-200" htmlFor="director">Director</label>
                    <input id="director"
                        formControlName="director"
                        name="director"
                        type="text"
                        class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                          />
                </div>

                <div>
                    <label class="text-white dark:text-gray-200" htmlFor="duracion">Duracion</label>
                    <input
                        formControlName="duracion"
                        name="duracion"
                        id="duracion"
                        type="text"
                        class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"
                        />
                </div>

            </div> 
            <div class=" w-full">
                <label class="block text-sm font-medium text-white">
                    Image
                </label>
                <div class="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                    <div class="space-y-1 text-center">
                        <svg class="mx-auto h-12 w-12 text-white" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                            <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        <div class="flex text-sm text-gray-600">
                            <label htmlFor="fileupload" class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                                <span class="">Upload a file</span>
                                <input id="fileupload"
                                 name="fileupload" 
                                 formControlName="file"
                                 type="file" 
                                 class="sr-only"
                                  />
                            </label>
                            <p class="pl-1 text-white">or drag and drop</p>
                        </div>
                        <p class="text-xs text-white">
                            PNG, JPG, GIF up to 10MB
                        </p>
                    </div>
                </div>
            </div>

            <div class="flex justify-end mt-6">
                <button
                    type="submit" 
                    class="border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-red-600 focus:outline-none focus:shadow-outline"
                >
                    Agregar
                </button>
            </div>
        </form>
    </section>

</div>
